version: 0.2

env:
  variables:
    GITOPS_REPO: "alvarolinarescabre/huma-counter-href-10-sites"
    ARGOCD_PUSH_BRANCH: "main"
    K8S_BASE_IMAGE_NAME: "huma-app-image"
    ARGOCD_APP_NAME: "huma-counter-href-10-sites"

phases:
  install:
    commands:
      - echo "Instalando dependencias (jq, git y kustomize)..."
      - apt-get update && apt-get install -y git jq
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - mv kustomize /usr/local/bin/

  build:
    commands:
      - echo "Obteniendo token de GitHub desde Secrets Manager..."
      - TOKEN_VALUE=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:312910855403:secret:eks-argocd-app-deploy-github-token-OwVLLP --query SecretString --output text | jq -r '.github_token' || aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:312910855403:secret:eks-argocd-app-deploy-github-token-OwVLLP --query SecretString --output text)

      - echo "Leyendo imagedefinitions.json inyectado por CodePipeline..."
      - cd /codebuild/output
      - ls -la
      - if [ ! -f "imagedefinitions.json" ]; then echo "Error: imagedefinitions.json no fue inyectado por CodePipeline."; exit 1; fi

      - echo "Leyendo imagedefinitions.json..."
      - IMAGE_URI=$(jq -r '.[0].imageUri' imagedefinitions.json)
      - IMAGE_TAG=$(echo "$IMAGE_URI" | awk -F':' '{print $2}')
      - IMAGE_NAME=$(echo "$IMAGE_URI" | awk -F':' '{print $1}')
      
      - if [ -z "$IMAGE_TAG" ] || [ "$IMAGE_TAG" = "$IMAGE_URI" ]; then echo "Error: No se pudo extraer el tag de la imagen."; exit 1; fi
      
      - echo "Nueva imagen detectada -> $IMAGE_URI"

      - echo "Clonando repositorio GitOps..."
      - REPO_URL="https://${TOKEN_VALUE}@github.com/${GITOPS_REPO}.git"
      - git clone "$REPO_URL" gitops_repo
      - cd gitops_repo
      - ls -la

      - TARGET_DIR="infraestructure/k8s/base"
      - cd "$TARGET_DIR"
      - echo "Actualizando kustomization.yaml con la nueva imagen usando Kustomize..."
      - kustomize edit set image ${K8S_BASE_IMAGE_NAME}=${IMAGE_NAME}:${IMAGE_TAG}
      - cat kustomization.yaml
      - ls -la
      
      - cd ../../../

      - echo "Configurando Git..."
      - git config user.email "codebuild@aws.local"
      - git config user.name "AWS CodeBuild"
      
      - git add "$TARGET_DIR/kustomization.yaml"
      
      - |
        if git diff --staged --quiet; then
          echo "No hay cambios en los manifiestos de Kubernetes. Saliendo..."
          exit 0
        fi
        
      - echo "Haciendo commit y push de los cambios..."
      - git commit -m "GitOps - actualización automática de imagen a ${IMAGE_TAG}"
      - git push origin HEAD:${ARGOCD_PUSH_BRANCH}