version: 0.2

env:
  variables:
    GITOPS_REPO: "alvarolinarescabre/huma-counter-href-10-sites"
    ARGOCD_PUSH_BRANCH: "main"

phases:
  install:
    commands:
      - echo "Instalando dependencias (jq, git y kustomize)..."
      - apt-get update && apt-get install -y git jq
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - mv kustomize /usr/local/bin/

  build:
    commands:
      - echo "Obteniendo token de GitHub desde Secrets Manager..."
      - TOKEN_VALUE=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:312910855403:secret:eks-argocd-app-deploy-github-token-OwVLLP --query SecretString --output text | jq -r '.github_token' || aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:312910855403:secret:eks-argocd-app-deploy-github-token-OwVLLP --query SecretString --output text)

      - echo "Buscando imagedefinitions.json..."
      - IMG_PATH=$(find . -maxdepth 6 -type f -name imagedefinitions.json -print -quit 2>/dev/null)
      - |
        if [ -z "$IMG_PATH" ]; then
          echo "Error: imagedefinitions.json no encontrado."
          exit 1
        fi
      
      - echo "Leyendo imagedefinitions.json desde $IMG_PATH"
      - IMAGE_URI=$(jq -r '.[0].imageUri' "$IMG_PATH")
      - |
        IMAGE_TAG=$(echo "$IMAGE_URI" | cut -d':' -f2)
      - IMAGE_NAME=$(echo "$IMAGE_URI" | cut -d':' -f1)
      
      - echo "Nueva imagen detectada -> $IMAGE_URI"

      - echo "Clonando repositorio GitOps..."
      - REPO_URL="https://${TOKEN_VALUE}@github.com/${GITOPS_REPO}.git"
      - git clone "$REPO_URL" gitops_repo
      - cd gitops_repo

      - TARGET_DIR="infraestructure/k8s/base"
      - |
        if [ ! -d "$TARGET_DIR" ]; then
          echo "Error: El directorio $TARGET_DIR no existe en el repositorio."
          exit 1
        fi
      
      - cd "$TARGET_DIR"
      - echo "Actualizando kustomization.yaml con la nueva imagen usando Kustomize..."
      # Kustomize edit set image expects 'name=newImage:tag' or 'name:tag'
      # Since IMAGE_NAME contains the full ECR repo path, we use it as the match key.
      - kustomize edit set image "${IMAGE_NAME}=${IMAGE_URI}"
      
      - cd ../../../

      - echo "Configurando Git..."
      - git config user.email "codebuild@aws.local"
      - git config user.name "AWS CodeBuild"
      
      - git add "$TARGET_DIR/kustomization.yaml"
      
      - |
        if git diff --staged --quiet; then
          echo "No hay cambios en los manifiestos de Kubernetes. Saliendo..."
          exit 0
        fi
        
      - echo "Haciendo commit y push de los cambios..."
      - git commit -m "GitOps: actualización automática de imagen a ${IMAGE_TAG}"
      - git push origin HEAD:${ARGOCD_PUSH_BRANCH}