version: 0.2

env:
  variables:
    # Si aplicación y manifiestos están en el mismo repo, solo necesitamos definirlo una vez
    GITOPS_REPO: "alvarolinarescabre/huma-counter-href-10-sites"
    ARGOCD_PUSH_BRANCH: "main"
  # Es muy recomendable pasar GITHUB_TOKEN a través de AWS Secrets Manager
  # secrets-manager:
  #   GITHUB_TOKEN: "arn:aws:secretsmanager:region:account:secret:my-github-token:token"

phases:
  install:
    commands:
      - echo "Instalando dependencias (jq, git y kustomize)..."
      - apt-get update && apt-get install -y git jq
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - mv kustomize /usr/local/bin/

  build:
    commands:
      - echo "Buscando imagedefinitions.json..."
      - IMG_PATH=$(find /codebuild/output . -maxdepth 6 -type f -name imagedefinitions.json -print -quit 2>/dev/null)
      
      - |
        if [ -z "$IMG_PATH" ]; then
          echo "Error: imagedefinitions.json no encontrado."
          exit 1
        fi
      
      - echo "Leyendo imagedefinitions.json desde $IMG_PATH"
      - IMAGE_URI=$(jq -r '.[0].imageUri' "$IMG_PATH")
      - IMAGE_TAG=$(echo "$IMAGE_URI" | awk -F: '{print $NF}')
      # Asume que el nombre base de la imagen en tu kustomization coincide con la parte antes del tag
      - IMAGE_NAME=$(echo "$IMAGE_URI" | sed 's/:.*$//')
      
      - echo "Nueva imagen detectada -> $IMAGE_URI"

      - echo "Clonando repositorio GitOps..."
      # Usamos el token si existe para autenticación HTTPS
      - REPO_URL="https://${GITHUB_TOKEN}@github.com/${GITOPS_REPO}.git"
      - git clone "$REPO_URL" gitops_repo
      - cd gitops_repo

      - TARGET_DIR="infraestructure/k8s/base"
      - |
        if [ ! -d "$TARGET_DIR" ]; then
          echo "Error: El directorio $TARGET_DIR no existe en el repositorio."
          exit 1
        fi
      
      - cd "$TARGET_DIR"
      - echo "Actualizando kustomization.yaml con la nueva imagen usando Kustomize..."
      
      # kustomize edit set image busca la imagen existente (IMAGE_NAME) y le asigna el nuevo URI/Tag
      - kustomize edit set image ${IMAGE_NAME}=${IMAGE_URI}
      
      # Regresamos a la raíz del repo clonado
      - cd ../../../

      - echo "Configurando Git..."
      - git config user.email "codebuild@aws.local"
      - git config user.name "AWS CodeBuild"
      
      - git add "$TARGET_DIR/kustomization.yaml"
      
      - |
        if git diff --staged --quiet; then
          echo "No hay cambios en los manifiestos de Kubernetes. Saliendo..."
          exit 0
        fi
        
      - echo "Haciendo commit y push de los cambios..."
      - git commit -m "GitOps: actualización automática de imagen a ${IMAGE_TAG}"
      
      # Si falla el push (ej. conflicto), el pipeline fallará y serás notificado.
      - git push origin HEAD:${ARGOCD_PUSH_BRANCH}