apiVersion: v1
kind: Secret
metadata:
  name: eks-argocd-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: eks-argocd-cluster
  server: ${CLUSTER_ARN}
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-argocd-cluster"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "${CLUSTER_CA}"
      }
    }
